source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'QueueSafeValue_Example' do
  pod 'QueueSafeValue', :path => '../'
end

target 'QueueSafeValue_Tests' do
  inherit! :search_paths
  pod 'QueueSafeValue', :path => '../'
  pod 'Quick', '~> 3.0.0'
  pod 'Nimble', '~> 8.1.2'
  pod 'SwiftLint'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
