# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Example app"
  lane :build do
    build_app(
      workspace: "Example/QueueSafeValue.xcworkspace",
      scheme: "QueueSafeValue-Example",
      silent: true,
      clean: true,
      skip_codesigning: true,
      skip_archive: true
    )
  end

  lane :test do
    run_tests(
      workspace: "Example/QueueSafeValue.xcworkspace",
      scheme: "QueueSafeValue-Example",
      test_without_building: true
    )
  end
end
