name: Build&Test

on:
  push:
    branches: [ feature/fastlane ]
 # pull_request:
 #   branches: [ dev/0.3 ]

jobs:
  iOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Cocoapods
      run: |
        gem install cocoapods
    - name: Install pods
      run: |
        pod install --project-directory=./Example
    - name: Install Bundle
      run: |
        bundle install
    - name: Setup Fastlane
      run: |
        gem install fastlane -NV
    - name: Build and Test
      run: |
        bundle exec fastlane test --verbose   
