name: Build

on:
  push:
    branches: [ feature/fastlane ]
 # pull_request:
 #   branches: [ dev/0.3 ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run fastlane setup
      run: |
        fastlane setup --verbose
    - name: Run fastlane build
      run: |
        bundle exec fastlane build --verbose
