name: Build

on:
  push:
    branches: [ feature/fastlane ]
 # pull_request:
 #   branches: [ dev/0.3 ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: |
        bundle install
    - name: Fastlane setup
      run: |
        brew install fastlane --verbose
    - name: Fastlane build
      run: |
        bundle exec fastlane build --verbose
