name: Build&Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ staging, master ]

jobs:
  iOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Cocoapods
      run: |
        gem install cocoapods
    - name: Install pods
      run: |
        pod install --project-directory=./Example
    - name: Install Bundle
      run: |
        bundle install
    - name: Check Podspec
      run: |
        pod lib lint  
    - name: Setup/Update Fastlane
      run: |
        gem install fastlane -NV
        bundle update fastlane
    - name: Build and Test
      run: |
        bundle exec fastlane test --verbose   
